- id: 1
  name: zunndamon normal
  speaker_uuid: 388f246b-8c41-4ac1-8e2d-5d79f3ff56d9
  style_id: 3
  speedScale: 1.3
  pitchScale: 0
  intonationScale: 1
  volumeScale: 1
  prePhonemeLength: 0.1
  postPhonemeLength: 0.1