[package]
name = "bot-db"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
redis = { version = "0.23.3", default-features = false, features = ["aio", "tokio-comp"] }
