[package]
name = "bot-config"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
tokio = { version = "1.34.0", features = ["fs"] }
serde = { version = "1.0.192", features = ["derive"] }
serde_yaml = "0.9.27"
